### ISSUE TITLE
Secrets format

### ISSUE THREAD

**Issue by neil-s** [thedataincubator/ds30#3]
What format does the `twitter_secrets.json.nogit` file need to be in, for Python to be able to read it into a dict? Is it key names and values, separated by spaces?

**Comment by SynbioLucas** [comment]
It needs to be in JSON format so that the SimpleJSON package can read it. Really, you can do whatever you want though as long as your keys/tokens get loaded into the `secrets` dictionary under the appropriate keys.

For the file, I used:

```
{
"api_key": "XXXX",
"api_secret": "XXXX",
"access_token": "XXXX",
"access_token_secret": "XXXX"
}
```

where obviously the XXXX values are yours. This seems to work, as far as I can tell.

**Comment by tianhuil** [comment]
Thanks @SynbioLucas: would you mind submitting a PR for the `README.md`?
